deepspeed --deepspeed configs/deepspeed/zero2.json \
    --live_version live1 \
    --train_datasets ego4d_goalstep_livechat_trainval ego4d_refined_narration_stream_train ego4d_refined_narration_stream_val \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing True \
    --evaluation_strategy no \
    --prediction_loss_only False \
    --save_strategy no \
    --learning_rate 0.0002 \
    --optim adamw_torch \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.05 \
    --logging_steps 10 \
    --dataloader_num_workers 16 \
    --bf16 True \
    --tf32 True \
    --report_to tensorboard \
    --augmentation True \
    --output_dir outputs/ego4d_live1_aug \
