torchrun --nproc_per_node=8 --standalone evaluate.py \
    --live_version live1+ \
    --eval_datasets coin_step_test coin_next_test coin_task_test coin_procedure_test coin_taskprocedure_test \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --prediction_loss_only False \
    --dataloader_num_workers 16 \
    --bf16 True \
    --tf32 True \
    --report_to tensorboard \
    --output_dir outputs/coin_benchmarks/live1+/ \
    --resume_from_checkpoint outputs/coin_benchmarks/live1+/
